# essential-playerinfo
# 配置版本。请勿修改此选项！
[version]
    version = "v3.3"

# 全局 Tab 列表
[tabList]
    enabled=true
    # `0` 生存，`1` 创造，`2` 冒险，`3` 旁观。
    displayMode=3

# 全局聊天
[message]
    enabled=true
    command-to-broadcast=false

# Ping 列表
[pingList]
    enabled = true

# 进服/切换提示
[connectionTips]
    enabled = true

# 记住我
[rememberMe]
    enabled = true

# 进服欢迎消息
[connectMessage]
    enabled = true
    serverName = "示例服务器"

# 自定义消息设置
[customText]
    enabled = false
    # v3.1.0（配置版本 v3.2）及以上需使用 MiniMessage 格式。
    # 可用 MiniMessage Viewer 预览：https://webui.adventure.kyori.net/
    connectionText = "<gray>%player%: 已连接到 <u><hover:show_text:'点击切换服务器。'><click:run_command:'/server %server%'>[%server%]</click></hover></u>。</gray>"
    serverChangeText = "<gray>%player%: <u><click:run_command:'/server %previousServer%'><hover:show_text:'点击切换服务器。'>[%previousServer%]</hover></click></u> -> <u><click:run_command:'/server %server%'><hover:show_text:'点击切换服务器。'>[%server%]</hover></click></u></gray>"
    disconnectionText = "<gray>%player%: 已退出服务器。</gray>"
    chatText = "<gray><u><click:run_command:'/server %server%'><hover:show_text:'点击切换服务器。'>[%server%]</hover></click></u> <%player%> "
    tabListText = "[%server%] %player%"
    connectionMessageText = "<yellow>-------------------------------\n欢迎来到 %serverName%！\n-------------------------------\n你可以点击下方服务器名称切换连接的服务器。\n%serverList%\n-------------------------------\n你可以使用 <u><light_purple><click:run_command:'/remember'><hover:show_text:'点击执行命令'>/remember</hover></click></light_purple></u> 设置默认连接服务器。\n-------------------------------</yellow>"
